### PR TITLE
machineNameToUnderscore should replace with underscores

### PR DESCRIPTION
**Pull request by tappleby**

### CODE REVIEW

**Comment by tappleby** [comment]
Was there an issue with the PR?

**Comment by patrickocoffeyo** [comment]
I'm not sure why this or https://github.com/patrickocoffeyo/distill/pull/4 was closed, both are great PRs. I'll re-open them, thanks for contributing! Sorry about that.

**Comment by patrickocoffeyo** [comment]
Good catch, I'm merging this :) I'll also promote the changes to the D8 branch :)

**Comment by tappleby** [comment]
:+1:

**Pull request merged**
